services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for your data

volumes:
  postgres_data: